marceloServiceB:
  appName: marcelo-adobe-service-b2
  image:
    repository: marcelovcpereira/adobe-test:serviceb2
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "1500m"
      memory: "4096Mi"
    requests:
      cpu: "1500m"
      memory: "4096Mi"

#########################
# Environment Variables #
#########################
  configMap:
    SERVICE_B_PORT: 8001