apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.marceloServiceB.appName }}
data:
  {{- range $key, $value := .Values.marceloServiceB.configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}