apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.marceloServiceB.appName }}
spec:
  ports:
    - port: {{ .Values.marceloServiceB.configMap.SERVICE_B_PORT }}
  selector:
    app: {{ .Values.marceloServiceB.appName }}
  clusterIP: None